version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:80"
  ctr2:
    container_name: my_python_app 
    image: python:3.8-slim
    command: ["python3", "-c", "print('Hello from Python container')"]

        
